### ISSUE TITLE
dropdown-indicator overlaps text in min-width scenario

### ISSUE THREAD

**Issue by jlsjonas** [enso-ui/dropdown#1]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

![image](https://user-images.githubusercontent.com/932193/54985053-65aa2a80-4fb0-11e9-8b2b-46e8f3d2deec.png)

### Steps to Reproduce
1. Add a simple dropdown (f.e.: settings sidebar, PageHeader)

### Expected behavior

![image](https://user-images.githubusercontent.com/932193/54985343-ed903480-4fb0-11e9-9a74-5db50c918b86.png)
(v2 behaviour)

### Actual behavior

![image](https://user-images.githubusercontent.com/932193/54985053-65aa2a80-4fb0-11e9-8b2b-46e8f3d2deec.png)

**Comment by aocneanu** [comment]
Recently I removed everything related to width / height from the dropdown and all the css should be handled from the local implementation.

**Comment by jlsjonas** [comment]
It shouldn't overlap out of itself though

**Comment by aocneanu** [comment]
@jlsjonas You're expecting here the select control to resize around the placeholder / option?

**Comment by jlsjonas** [comment]
I expect the dropdown-indicator to be accounted for in the _minimum width_ scenario when visible.

This would likely mean adding a padding-right to the `<button>` if `!disabled`
i.e. extending `:class="{ 'has-error': hasError }"` to `:class="{ 'has-error': hasError, 'indicator-padding': !disabled }"
I can PR if you'd like, but as it requires manual npm publishing either way (you don't have that automated _yet_, right?) it might be faster for you if you do it directly.
